"""initial

Revision ID: 8d51900556e1
Revises: 
Create Date: 2026-06-02 04:44:28.245927

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '8d51900556e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
