"""add avatar_url and portfolio_urls to users

Revision ID: e46dd5be3661
Revises: b14af240455b
Create Date: 2026-06-06 03:00:57.376509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46dd5be3661'
down_revision: Union[str, Sequence[str], None] = 'b14af240455b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('portfolio_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'portfolio_urls')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
